[package]
name = "zfs-cmd-api"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]

[dependencies]
failure = "*"
failure_derive = "*"
fmt-extra = "*"
bitflags = "*"
enumflags2 = "^0.5"
enumflags2_derive = "^0.5"
shell-words = "0.1"
